name: "Build"
on:
  pull_request:
jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Run Checkout"
        uses: "actions/checkout@v3"
      - name: "Setup Node"
        uses: "actions/setup-node@v4"
        with:
          node-version: "18.x"
      - name: "Cache Dependencies"
        uses: "actions/cache@v3"
        with:
          key: "${{runner.os}}-npm-${{hashFiles('**/package-lock.json')}}"
          path: "~/.npm"
          restore-keys: "${{runner.os}}-npm-${{hashFiles('**/package-lock.json')}}"
      - name: "Install Dependencies"
        run: "npm ci"
      - name: "Run Eslint"
        run: "npm run lint:eslint"
      - name: "Run Prettier"
        run: "npm run lint:prettier"
      - name: "Run Build"
        env:
          INNGEST_EVENT_KEY: "ci"
          MONGODB_URI: "${{secrets.MONGODB_URI}}"
          NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA: "${{github.sha}}"
          TOKEN_SIGNING_KEY: "${{secrets.TOKEN_SIGNING_KEY}}"
        run: "npm run build"
