name: Build
on:
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Run Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          key: ${{runner.os}}-npm-${{hashFiles('**/package-lock.json')}}
          path: ~/.npm
          restore-keys: |
            ${{runner.os}}-npm-${{hashFiles('**/package-lock.json')}}
            ${{runner.os}}-npm-
      - name: Install Dependencies
        run: npm ci
      - name: Run Eslint
        run: npm run lint:eslint
      - name: Run Prettier
        run: npm run lint:prettier
      - name: Run Build
        env:
          DISCORD_BOT_TOKEN: ${{secrets.DISCORD_BOT_TOKEN}}
          DISCORD_CLIENT_ID: ${{secrets.DISCORD_CLIENT_ID}}
          DISCORD_CLIENT_SECRET: ${{secrets.DISCORD_CLIENT_SECRET}}
          DISCORD_PUBLIC_KEY: ${{secrets.DISCORD_PUBLIC_KEY}}
          INNGEST_EVENT_KEY: ${{secrets.INNGEST_EVENT_KEY}}
          INNGEST_SIGNING_KEY: ${{secrets.INNGEST_SIGNING_KEY}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          OPENWEATHER_API_KEY: ${{secrets.OPENWEATHER_API_KEY}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          TOKEN_SIGNING_KEY: ${{secrets.TOKEN_SIGNING_KEY}}
        run: npm run build
